djangosite/djangosite/urls.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Curate life's moments.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
URL configuration for djangosite project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, path

urlpatterns = [
    path('', include('vestige.urls')),
]

djangosite/vestige/urls.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Curate life's moments.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from django.conf import settings

from . import views

app_name = 'vestige'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('view/', views.view, name='view'),
    path('view/<path:path>/', views.view, name='view'),
]

if settings.REGISTRATION:
    urlpatterns += path('register/', views.register_user,
                        name='register_user'),

djangosite/vestige/models.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Curate life's moments.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

djangosite/vestige/views.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Curate life's moments.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.encoding import iri_to_uri

# For Matrix image uploads
from asgiref.sync import async_to_sync, sync_to_async
import aiofiles.os
import magic
import os
from nio import AsyncClient, UploadResponse
from PIL import Image

import frontmatter
import hashlib
import time
import string


@sync_to_async
@login_required
@async_to_sync
async def view(request, path=None):
    if request.method == "GET":

        photos = []
        context = {}

        if path:
            vestigeid = path.split("/")[-1]
            p = getthing(vestigeid)
            context["form"] = {'description': p['description']}

            if vestigeid.startswith("photo"):
                context["feature"] = p
            else:
                photos = listthing(vestigeid)
        elif "type" in request.GET:
            photos = getrootthings(request.GET["type"])
        else:
            photos = getanythings("photo")

        context["photos"] = photos
        context["albums"] = getanythings("album")
        context["people"] = getanythings("people")

        return render(request, 'vestige/index.html', context)
    elif request.method == "POST":
        if "action" in request.POST:
            if request.POST["action"] == "remove":
                ids = getphotoids(request)
                if path:
                    vestigeid = path.split("/")[-1]
                    removethings(ids, vestigeid)
                else:
                    removethings(ids)
            if request.POST["action"] == "update":
                path = path.split("/")[-1]
                updatedescription(path, request.POST["photodesc"])
            if request.POST["action"] == "add":
                ids = getphotoids(request)

                if "new" in request.POST and request.POST["new"] != "":
                    # Convert new to a safe segment name
                    # https://en.wikipedia.org/wiki/URL_encoding
                    allowable = string.ascii_letters + string.digits + "-_.~"
                    allowablename = "".join([c for c in request.POST["new"] if
                                             c in allowable])
                    addnewthingtotree(allowablename, request.POST["new"],
                                      request.POST["radioType"].lower(), ids)

                elif "existing" in request.POST:
                    updatethingintree(request.POST['existing'], ids)
            if request.POST["action"] == "chat":
                ids = getphotoids(request)
                for photoid in ids:
                    p = getthing(photoid)
                    await matrixsendimage(os.path.join(settings.PHOTO_DIR,
                                                       p['path']))

        return HttpResponseRedirect("#")


# ------------------------------------------------------------------------------
# Request Utilities
# ------------------------------------------------------------------------------

def getphotoids(request):
    photoids = []
    for key in request.POST:
        if key[:5] == "check":
            photoids.append(request.POST[key])
    return photoids


# ------------------------------------------------------------------------------
# Reading from storage
# ------------------------------------------------------------------------------

def listthing(vestigeid):
    metadatafiles = []

    with open(os.path.join(settings.STORAGE_DIR, "README.md"), "r") as f:
        post = frontmatter.load(f)

    if vestigeid in post["tree"]["leaves"]:
        leaf = post["tree"]["leaves"][vestigeid]
        for entry in leaf:
            metadatafiles.append(os.path.join(settings.STORAGE_DIR, entry))

    return readmetadatafiles(metadatafiles)


def getrootthings(type):
    metadatafiles = []
    with open(os.path.join(settings.STORAGE_DIR, "README.md"), "r") as f:
        post = frontmatter.load(f)
    for key in post["tree"]["roots"]:
        if key.startswith(type):
            metadatafiles.append(os.path.join(settings.STORAGE_DIR, key))
    return readmetadatafiles(metadatafiles)


def getanythings(type):
    metadatafiles = []
    with open(os.path.join(settings.STORAGE_DIR, "README.md"), "r") as f:
        post = frontmatter.load(f)
    for key in post["tree"]["leaves"]:
        if key.startswith(type):
            metadatafiles.append(os.path.join(settings.STORAGE_DIR, key))
    return readmetadatafiles(metadatafiles)


def getthing(id):
    metadatafiles = os.path.join(settings.STORAGE_DIR, id)
    return readmetadatafiles([metadatafiles])[0]


def readmetadatafiles(metadatafiles):
    results = []

    # Load the tree
    with open(os.path.join(settings.STORAGE_DIR, "README.md"), "r") as f:
        tree = frontmatter.load(f)["tree"]

    for metadata in metadatafiles:
        with open(metadata, "r") as f:
            type = os.path.split(metadata)[1].split("-")[0]
            post = frontmatter.load(f)

            resultid = os.path.split(metadata)[1]
            title = "UNSET"
            thumbnail = []
            if type == "album":
                title = post["name"]
                # TODO: Their thumbnail is the first photo underneath them
            elif type == "photo":
                title = post["originalfilename"]
                thumbnail = (f"{settings.STATICFILES_DIRS[0][0]}/" +
                             f"{post['thumbnails'][0]}")
            elif type == "people":
                title = post["name"]
            elif type == "folder":
                title = post["name"]

            result = {"id": resultid,
                      "title": title,
                      "description": post.content,
                      "thumbnail": thumbnail}

            if type == "photo":
                result["path"] = post['path']

            result["backlinks"] = getbacklinks(tree,
                                               os.path.split(metadata)[1])

            results.append(result)
    return results


def getbacklinks(tree, vestigeid):
    backlinks = []
    for leaf in tree["leaves"]:
        if vestigeid in tree["leaves"][leaf]:
            with open(os.path.join(settings.STORAGE_DIR, leaf), "r") as f:
                name = frontmatter.load(f)["name"]

            backlink = {"id": leaf,
                        "type": leaf.split("-")[0],
                        "name": name}
            backlinks.append(backlink)
    return backlinks


# ------------------------------------------------------------------------------
# Writing to storage
# ------------------------------------------------------------------------------

def updatedescription(id, description):
    metadata = os.path.join(settings.STORAGE_DIR, id)
    post = frontmatter.Post("")

    if os.path.exists(metadata):
        with open(metadata, "r") as f:
            post = frontmatter.load(f)
    else:
        os.makedirs(os.path.dirname(metadata), exist_ok=True)

    post.content = description

    with open(metadata, "w") as f:
        f.write(frontmatter.dumps(post))


def addnewthingtotree(new, name, type, ids):
    # TODO: we must check for collisions also tho
    # TODO: don't just use albumnew on the fs, we should stdz name

    # TODO: Check input
    if type == "person":
        type = "people"

    newstamped = f"{new}{time.time()}"
    # https://stackoverflow.com/a/62699124/28170
    hash = hashlib.shake_256(newstamped.encode()).hexdigest(5)
    path = f"{type}-{hash}-{new}.md"

    # Create the metadata
    metadata = os.path.join(settings.STORAGE_DIR, path)
    if not os.path.exists(metadata):
        post = frontmatter.Post("")
        # TODO: Here we need to fill in the right metadata
        # depending on what we've just created
        post["name"] = name
        with open(metadata, "w") as f:
            f.write(frontmatter.dumps(post))

    # Update tree
    metadata = os.path.join(settings.STORAGE_DIR, "README.md")
    with open(metadata, "r") as f:
        post = frontmatter.load(f)
    # Put in the tree at root
    post["tree"]["roots"][path] = dict()
    # Put all the ids underneath in leaves
    post["tree"]["leaves"][path] = {x: {} for x in ids}

    with open(metadata, "w") as f:
        f.write(frontmatter.dumps(post))


def updatethingintree(name, ids):
    # Update tree
    metadata = os.path.join(settings.STORAGE_DIR, "README.md")
    with open(metadata, "r") as f:
        post = frontmatter.load(f)
    # Get current children
    current = post["tree"]["leaves"][name]
    # Add all the ids
    post["tree"]["leaves"][name] = current | {x: {} for x in ids}

    with open(metadata, "w") as f:
        f.write(frontmatter.dumps(post))


def removethings(ids, name=None):

djangosite/vestige/templates/vestige/base_auth.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: AGPL-3.0-or-later

Curate life's moments.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

{% load static %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'vendor/toastui-editor.css' %}" />
  {% endblock %}
  <title>{% block title %}Vestige{% endblock %}</title>
  <link rel="icon" href="{% static 'vestige/favicon.svg' %}">
</head>
<body> 
  {% block scripts %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script src="{% static 'vendor/bundle-toastui-editor.js' %}"></script>
  {% endblock %}

  <main class="d-flex flex-nowrap vh-100">
    <div class="d-flex flex-column m-3">
      <a class="text-decoration-none mb-2" href="/">
        <img class="me-2" src="{% static 'vestige/favicon.svg' %}" width="53" height="51">
        <span class="fs-5 fw-semibold">Vestige</span>
      </a>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item"><a class="nav-link" href="/view/">Latest</a></li>
        <li class="nav-item"><a class="nav-link" href="/view/?type=album">Albums</a></li>
        <li class="nav-item"><a class="nav-link" href="/view/?type=folder">Folders</a></li>
        <li class="nav-item"><a class="nav-link" href="/view/?type=people">People</a></li>
      </ul>
    </div>

    <div class="d-flex flex-grow-1 flex-column m-3">
      <div class="d-flex flex-row-reverse mb-2">
        <a class="" href="/logout">
          <img class="" alt="Logout" src="{% static 'vestige/logout.png' %}" width="51" height="51">
        </a>
      </div>
      <div class="d-flex flex-column overflow-auto">
        {% block content %} {% endblock %}
      </div>
    </div>
  </main>
</body>
</html>

djangosite/vestige/templates/vestige/base_unauth.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: AGPL-3.0-or-later

Curate life's moments.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

{% load static %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block styles %}
    {% bootstrap_css %}
  {% endblock %}
  <title>{% block title %}Vestige{% endblock %}</title>
  <link rel="icon" href="{% static 'vestige/favicon.svg' %}">
</head>
<body> 
  {% block scripts %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
  {% endblock %}
  {% block content %} {% endblock %}
</body>
</html>

djangosite/vestige/templates/vestige/login.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: AGPL-3.0-or-later

Curate life's moments.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

{% extends "vestige/base_unauth.html" %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Login{% endblock %}
{% block content %}

<div class="container vh-100">
  <form class="container-sm mt-5" action="{% url 'vestige:login_user' %}" method="post" style="max-width: 330px;">
    <img class="mx-auto d-block img-fluid" src="{% static 'vestige/logo.png' %}" alt="" width="300" height="119">
    <h3 class="mb-3 fw-normal text-center">Please sign in</h3>
    {% csrf_token %}
    <div class="alert alert-warning alert-dismissible" role="alert">
      <strong>Caution: </strong>this is a prototype, insecure and unreliable. Data is deleted regularly. Don't enter any private information.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    {% if demo %}
    <p class="text-center">Login with demo/demo{% if registration %} or <a href="/register">sign up</a>{% endif %}</p>
    {% endif %}
    <div class="form-group my-1">
      <input type="text" class="form-control" name="username" id="username" placeholder="Username" {% if demo %}value="demo" {% endif %}>
    </div>
    <div class="form-group">
      <input type="password" class="form-control" name="password" id="password" placeholder="Password" {% if demo %}value="demo" {% endif %}>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="w-100 mt-3 btn btn-lg btn-primary">Login</button>
  </form>
  {% if registration %}
    <p class="text-center my-3">Don't have an account? <a href="/register">Sign up</a></p>
  {% endif %}
  <p class="text-center my-3 text-muted">Open source - find us on <a href="https://gitlab.com/thegalagic/vestige">GitLab</a></p>
</div>
{% endblock %}

djangosite/vestige/templates/vestige/register.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: AGPL-3.0-or-later

Curate life's moments.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/vestige/AUTHORS.md)

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

{% extends "vestige/base_unauth.html" %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Register{% endblock %}
{% block content %}

<div class="container vh-100">
  <form class="container-sm mt-5" action="{% url 'vestige:register_user' %}" method="post" style="max-width: 330px;">
    <img class="mx-auto d-block img-fluid" src="{% static 'vestige/logo.png' %}" alt="" width="300" height="119">
    <h3 class="mb-3 fw-normal text-center">Create your account</h3>
    {% csrf_token %}
    <div class="alert alert-warning alert-dismissible" role="alert">
      <strong>Caution: </strong>this is a prototype, insecure and unreliable. Data is deleted regularly. Don't enter any private information.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <div class="form-group my-1">
      <input type="text" class="form-control" name="username" id="username" placeholder="Username">
    </div>
    <div class="form-group">
      <input type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <button type="submit" class="w-100 mt-3 btn btn-lg btn-primary">Register</button>
  </form>
  <p class="text-center my-3">Already have an account? <a href="/login">Sign in</a></p>
  <p class="text-center my-3 text-muted">Open source - find us on <a href="https://gitlab.com/thegalagic/vestige">GitLab</a></p>
</div>
{% endblock %}